// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"xcore/dao/model"
)

func newSysGenTableColumn(db *gorm.DB, opts ...gen.DOOption) sysGenTableColumn {
	_sysGenTableColumn := sysGenTableColumn{}

	_sysGenTableColumn.sysGenTableColumnDo.UseDB(db, opts...)
	_sysGenTableColumn.sysGenTableColumnDo.UseModel(&model.SysGenTableColumn{})

	tableName := _sysGenTableColumn.sysGenTableColumnDo.TableName()
	_sysGenTableColumn.ALL = field.NewAsterisk(tableName)
	_sysGenTableColumn.UID = field.NewString(tableName, "uid")
	_sysGenTableColumn.TableID = field.NewString(tableName, "table_id")
	_sysGenTableColumn.ColumnUpUpName = field.NewString(tableName, "column_up_up_name")
	_sysGenTableColumn.ColumnLowUpName = field.NewString(tableName, "column_low_up_name")
	_sysGenTableColumn.ColumnName = field.NewString(tableName, "column_name")
	_sysGenTableColumn.ColumnComment = field.NewString(tableName, "column_comment")
	_sysGenTableColumn.ColumnLength = field.NewString(tableName, "column_length")
	_sysGenTableColumn.ColumnType = field.NewString(tableName, "column_type")
	_sysGenTableColumn.ColumnTsType = field.NewString(tableName, "column_ts_type")
	_sysGenTableColumn.IsRequired = field.NewBool(tableName, "is_required")
	_sysGenTableColumn.IsBase = field.NewBool(tableName, "is_base")
	_sysGenTableColumn.IsEdit = field.NewBool(tableName, "is_edit")
	_sysGenTableColumn.IsList = field.NewBool(tableName, "is_list")
	_sysGenTableColumn.IsQuery = field.NewBool(tableName, "is_query")
	_sysGenTableColumn.QueryType = field.NewString(tableName, "query_type")
	_sysGenTableColumn.HTMLType = field.NewString(tableName, "html_type")
	_sysGenTableColumn.DictType = field.NewString(tableName, "dict_type")
	_sysGenTableColumn.Sort = field.NewInt32(tableName, "sort")
	_sysGenTableColumn.Version = field.NewInt32(tableName, "version")
	_sysGenTableColumn.CreateUID = field.NewInt32(tableName, "create_uid")
	_sysGenTableColumn.CreateBy = field.NewString(tableName, "create_by")
	_sysGenTableColumn.CreateAt = field.NewTime(tableName, "create_at")
	_sysGenTableColumn.UpdateAt = field.NewTime(tableName, "update_at")
	_sysGenTableColumn.UpdateUID = field.NewInt32(tableName, "update_uid")
	_sysGenTableColumn.SoftDeleteTag = field.NewInt32(tableName, "soft_delete_tag")
	_sysGenTableColumn.UpdateBy = field.NewString(tableName, "update_by")

	_sysGenTableColumn.fillFieldMap()

	return _sysGenTableColumn
}

// sysGenTableColumn 代码生成字段表
type sysGenTableColumn struct {
	sysGenTableColumnDo sysGenTableColumnDo

	ALL             field.Asterisk
	UID             field.String // 软删除编辑
	TableID         field.String // 表ID
	ColumnUpUpName  field.String // 字段upup
	ColumnLowUpName field.String // 字段lowup
	ColumnName      field.String // 字段名
	ColumnComment   field.String // 列描述
	ColumnLength    field.String // 列长度
	ColumnType      field.String // go类型
	ColumnTsType    field.String // ts类型
	IsRequired      field.Bool   // 是否必填: [1=是, 0=否]
	IsBase          field.Bool   // 是否基础字段
	IsEdit          field.Bool   // 是否编辑字段: [1=是, 0=否]
	IsList          field.Bool   // 是否列表字段: [1=是, 0=否]
	IsQuery         field.Bool   // 是否查询字段: [1=是, 0=否]
	QueryType       field.String // 查询方式: [等于、不等于、大于、小于、范围]
	HTMLType        field.String // 显示类型: [文本框、文本域、下拉框、复选框、单选框、日期控件]
	DictType        field.String // 字典类型
	Sort            field.Int32  // 排序编号
	Version         field.Int32  // 乐观锁
	CreateUID       field.Int32  // 创建者uid
	CreateBy        field.String // 创建者
	CreateAt        field.Time   // 创建时间
	UpdateAt        field.Time   // 更新时间
	UpdateUID       field.Int32  // 更新者uid
	SoftDeleteTag   field.Int32  // 软删除标记
	UpdateBy        field.String // 更新者

	fieldMap map[string]field.Expr
}

func (s sysGenTableColumn) Table(newTableName string) *sysGenTableColumn {
	s.sysGenTableColumnDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysGenTableColumn) As(alias string) *sysGenTableColumn {
	s.sysGenTableColumnDo.DO = *(s.sysGenTableColumnDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysGenTableColumn) updateTableName(table string) *sysGenTableColumn {
	s.ALL = field.NewAsterisk(table)
	s.UID = field.NewString(table, "uid")
	s.TableID = field.NewString(table, "table_id")
	s.ColumnUpUpName = field.NewString(table, "column_up_up_name")
	s.ColumnLowUpName = field.NewString(table, "column_low_up_name")
	s.ColumnName = field.NewString(table, "column_name")
	s.ColumnComment = field.NewString(table, "column_comment")
	s.ColumnLength = field.NewString(table, "column_length")
	s.ColumnType = field.NewString(table, "column_type")
	s.ColumnTsType = field.NewString(table, "column_ts_type")
	s.IsRequired = field.NewBool(table, "is_required")
	s.IsBase = field.NewBool(table, "is_base")
	s.IsEdit = field.NewBool(table, "is_edit")
	s.IsList = field.NewBool(table, "is_list")
	s.IsQuery = field.NewBool(table, "is_query")
	s.QueryType = field.NewString(table, "query_type")
	s.HTMLType = field.NewString(table, "html_type")
	s.DictType = field.NewString(table, "dict_type")
	s.Sort = field.NewInt32(table, "sort")
	s.Version = field.NewInt32(table, "version")
	s.CreateUID = field.NewInt32(table, "create_uid")
	s.CreateBy = field.NewString(table, "create_by")
	s.CreateAt = field.NewTime(table, "create_at")
	s.UpdateAt = field.NewTime(table, "update_at")
	s.UpdateUID = field.NewInt32(table, "update_uid")
	s.SoftDeleteTag = field.NewInt32(table, "soft_delete_tag")
	s.UpdateBy = field.NewString(table, "update_by")

	s.fillFieldMap()

	return s
}

func (s *sysGenTableColumn) WithContext(ctx context.Context) *sysGenTableColumnDo {
	return s.sysGenTableColumnDo.WithContext(ctx)
}

func (s sysGenTableColumn) TableName() string { return s.sysGenTableColumnDo.TableName() }

func (s sysGenTableColumn) Alias() string { return s.sysGenTableColumnDo.Alias() }

func (s sysGenTableColumn) Columns(cols ...field.Expr) gen.Columns {
	return s.sysGenTableColumnDo.Columns(cols...)
}

func (s *sysGenTableColumn) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysGenTableColumn) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 26)
	s.fieldMap["uid"] = s.UID
	s.fieldMap["table_id"] = s.TableID
	s.fieldMap["column_up_up_name"] = s.ColumnUpUpName
	s.fieldMap["column_low_up_name"] = s.ColumnLowUpName
	s.fieldMap["column_name"] = s.ColumnName
	s.fieldMap["column_comment"] = s.ColumnComment
	s.fieldMap["column_length"] = s.ColumnLength
	s.fieldMap["column_type"] = s.ColumnType
	s.fieldMap["column_ts_type"] = s.ColumnTsType
	s.fieldMap["is_required"] = s.IsRequired
	s.fieldMap["is_base"] = s.IsBase
	s.fieldMap["is_edit"] = s.IsEdit
	s.fieldMap["is_list"] = s.IsList
	s.fieldMap["is_query"] = s.IsQuery
	s.fieldMap["query_type"] = s.QueryType
	s.fieldMap["html_type"] = s.HTMLType
	s.fieldMap["dict_type"] = s.DictType
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["version"] = s.Version
	s.fieldMap["create_uid"] = s.CreateUID
	s.fieldMap["create_by"] = s.CreateBy
	s.fieldMap["create_at"] = s.CreateAt
	s.fieldMap["update_at"] = s.UpdateAt
	s.fieldMap["update_uid"] = s.UpdateUID
	s.fieldMap["soft_delete_tag"] = s.SoftDeleteTag
	s.fieldMap["update_by"] = s.UpdateBy
}

func (s sysGenTableColumn) clone(db *gorm.DB) sysGenTableColumn {
	s.sysGenTableColumnDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysGenTableColumn) replaceDB(db *gorm.DB) sysGenTableColumn {
	s.sysGenTableColumnDo.ReplaceDB(db)
	return s
}

type sysGenTableColumnDo struct{ gen.DO }

func (s sysGenTableColumnDo) Debug() *sysGenTableColumnDo {
	return s.withDO(s.DO.Debug())
}

func (s sysGenTableColumnDo) WithContext(ctx context.Context) *sysGenTableColumnDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysGenTableColumnDo) ReadDB() *sysGenTableColumnDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysGenTableColumnDo) WriteDB() *sysGenTableColumnDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysGenTableColumnDo) Session(config *gorm.Session) *sysGenTableColumnDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysGenTableColumnDo) Clauses(conds ...clause.Expression) *sysGenTableColumnDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysGenTableColumnDo) Returning(value interface{}, columns ...string) *sysGenTableColumnDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysGenTableColumnDo) Not(conds ...gen.Condition) *sysGenTableColumnDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysGenTableColumnDo) Or(conds ...gen.Condition) *sysGenTableColumnDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysGenTableColumnDo) Select(conds ...field.Expr) *sysGenTableColumnDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysGenTableColumnDo) Where(conds ...gen.Condition) *sysGenTableColumnDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysGenTableColumnDo) Order(conds ...field.Expr) *sysGenTableColumnDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysGenTableColumnDo) Distinct(cols ...field.Expr) *sysGenTableColumnDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysGenTableColumnDo) Omit(cols ...field.Expr) *sysGenTableColumnDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysGenTableColumnDo) Join(table schema.Tabler, on ...field.Expr) *sysGenTableColumnDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysGenTableColumnDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysGenTableColumnDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysGenTableColumnDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysGenTableColumnDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysGenTableColumnDo) Group(cols ...field.Expr) *sysGenTableColumnDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysGenTableColumnDo) Having(conds ...gen.Condition) *sysGenTableColumnDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysGenTableColumnDo) Limit(limit int) *sysGenTableColumnDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysGenTableColumnDo) Offset(offset int) *sysGenTableColumnDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysGenTableColumnDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysGenTableColumnDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysGenTableColumnDo) Unscoped() *sysGenTableColumnDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysGenTableColumnDo) Create(values ...*model.SysGenTableColumn) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysGenTableColumnDo) CreateInBatches(values []*model.SysGenTableColumn, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysGenTableColumnDo) Save(values ...*model.SysGenTableColumn) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysGenTableColumnDo) First() (*model.SysGenTableColumn, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysGenTableColumn), nil
	}
}

func (s sysGenTableColumnDo) Take() (*model.SysGenTableColumn, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysGenTableColumn), nil
	}
}

func (s sysGenTableColumnDo) Last() (*model.SysGenTableColumn, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysGenTableColumn), nil
	}
}

func (s sysGenTableColumnDo) Find() ([]*model.SysGenTableColumn, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysGenTableColumn), err
}

func (s sysGenTableColumnDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysGenTableColumn, err error) {
	buf := make([]*model.SysGenTableColumn, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysGenTableColumnDo) FindInBatches(result *[]*model.SysGenTableColumn, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysGenTableColumnDo) Attrs(attrs ...field.AssignExpr) *sysGenTableColumnDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysGenTableColumnDo) Assign(attrs ...field.AssignExpr) *sysGenTableColumnDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysGenTableColumnDo) Joins(fields ...field.RelationField) *sysGenTableColumnDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysGenTableColumnDo) Preload(fields ...field.RelationField) *sysGenTableColumnDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysGenTableColumnDo) FirstOrInit() (*model.SysGenTableColumn, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysGenTableColumn), nil
	}
}

func (s sysGenTableColumnDo) FirstOrCreate() (*model.SysGenTableColumn, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysGenTableColumn), nil
	}
}

func (s sysGenTableColumnDo) FindByPage(offset int, limit int) (result []*model.SysGenTableColumn, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysGenTableColumnDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysGenTableColumnDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysGenTableColumnDo) Delete(models ...*model.SysGenTableColumn) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysGenTableColumnDo) withDO(do gen.Dao) *sysGenTableColumnDo {
	s.DO = *do.(*gen.DO)
	return s
}
