// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"xcore/dao/model"
)

func newSysMenu(db *gorm.DB, opts ...gen.DOOption) sysMenu {
	_sysMenu := sysMenu{}

	_sysMenu.sysMenuDo.UseDB(db, opts...)
	_sysMenu.sysMenuDo.UseModel(&model.SysMenu{})

	tableName := _sysMenu.sysMenuDo.TableName()
	_sysMenu.ALL = field.NewAsterisk(tableName)
	_sysMenu.ID = field.NewInt32(tableName, "id")
	_sysMenu.Name = field.NewString(tableName, "name")
	_sysMenu.Path = field.NewString(tableName, "path")
	_sysMenu.Redirect = field.NewString(tableName, "redirect")
	_sysMenu.ParentID = field.NewInt32(tableName, "parent_id")
	_sysMenu.Component = field.NewString(tableName, "component")
	_sysMenu.Props = field.NewInt32(tableName, "props")
	_sysMenu.Status = field.NewInt32(tableName, "status")
	_sysMenu.MetaIconType = field.NewString(tableName, "meta_icon_type")
	_sysMenu.MetaOrder = field.NewInt32(tableName, "meta_order")
	_sysMenu.MetaConstant = field.NewInt32(tableName, "meta_constant")
	_sysMenu.MetaHideInMenu = field.NewInt32(tableName, "meta_hide_in_menu")
	_sysMenu.MetaRequiresAuth = field.NewInt32(tableName, "meta_requires_auth")
	_sysMenu.MetaIcon = field.NewString(tableName, "meta_icon")
	_sysMenu.MetaLocalIcon = field.NewString(tableName, "meta_local_icon")
	_sysMenu.MetaI18nKey = field.NewString(tableName, "meta_i18n_key")
	_sysMenu.MetaHref = field.NewString(tableName, "meta_href")
	_sysMenu.MetaKeepAlive = field.NewInt32(tableName, "meta_keep_alive")
	_sysMenu.MetaTitle = field.NewString(tableName, "meta_title")
	_sysMenu.MetaActiveMenu = field.NewString(tableName, "meta_active_menu")
	_sysMenu.MetaMultiTab = field.NewInt32(tableName, "meta_multi_tab")
	_sysMenu.MetaFixedInTab = field.NewInt32(tableName, "meta_fixed_in_tab")
	_sysMenu.MetaQuery = field.NewString(tableName, "meta_query")
	_sysMenu.Version = field.NewInt32(tableName, "version")
	_sysMenu.SoftDeleteTag = field.NewInt32(tableName, "soft_delete_tag")
	_sysMenu.UpdateTime = field.NewTime(tableName, "update_time")
	_sysMenu.UpdateUID = field.NewInt32(tableName, "update_uid")
	_sysMenu.CreateUID = field.NewInt32(tableName, "create_uid")
	_sysMenu.CreateBy = field.NewString(tableName, "create_by")
	_sysMenu.CreateTime = field.NewTime(tableName, "create_time")
	_sysMenu.UpdateBy = field.NewString(tableName, "update_by")

	_sysMenu.fillFieldMap()

	return _sysMenu
}

// sysMenu 系统菜单
type sysMenu struct {
	sysMenuDo sysMenuDo

	ALL              field.Asterisk
	ID               field.Int32  // 主键
	Name             field.String // 菜单项名称
	Path             field.String // 路径
	Redirect         field.String // 重定向地址
	ParentID         field.Int32  // 父菜单uuid
	Component        field.String // 组件名称
	Props            field.Int32  // 地址参数 u/:id
	Status           field.Int32  // 是否启用
	MetaIconType     field.String // icon类型 0本地 1iconify
	MetaOrder        field.Int32  // 排序
	MetaConstant     field.Int32  // 常量路由
	MetaHideInMenu   field.Int32  // 菜单中隐藏
	MetaRequiresAuth field.Int32  // 是否需要认证
	MetaIcon         field.String // 元图标
	MetaLocalIcon    field.String // 本地元图标
	MetaI18nKey      field.String // 国际化标题
	MetaHref         field.String // 外部连接
	MetaKeepAlive    field.Int32  // 缓存该路由
	MetaTitle        field.String // 元数据标题
	MetaActiveMenu   field.String // 激活的菜单键
	MetaMultiTab     field.Int32  // 多个标签页
	MetaFixedInTab   field.Int32  // 标签固定位置
	MetaQuery        field.String // 默认携带参数
	Version          field.Int32  // 乐观锁
	SoftDeleteTag    field.Int32  // 软删除标记
	UpdateTime       field.Time   // 更新时间
	UpdateUID        field.Int32  // 更新者uuid
	CreateUID        field.Int32  // 创建者uuid
	CreateBy         field.String // 创建者
	CreateTime       field.Time   // 创建时间
	UpdateBy         field.String // 更新者名称

	fieldMap map[string]field.Expr
}

func (s sysMenu) Table(newTableName string) *sysMenu {
	s.sysMenuDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysMenu) As(alias string) *sysMenu {
	s.sysMenuDo.DO = *(s.sysMenuDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysMenu) updateTableName(table string) *sysMenu {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.Name = field.NewString(table, "name")
	s.Path = field.NewString(table, "path")
	s.Redirect = field.NewString(table, "redirect")
	s.ParentID = field.NewInt32(table, "parent_id")
	s.Component = field.NewString(table, "component")
	s.Props = field.NewInt32(table, "props")
	s.Status = field.NewInt32(table, "status")
	s.MetaIconType = field.NewString(table, "meta_icon_type")
	s.MetaOrder = field.NewInt32(table, "meta_order")
	s.MetaConstant = field.NewInt32(table, "meta_constant")
	s.MetaHideInMenu = field.NewInt32(table, "meta_hide_in_menu")
	s.MetaRequiresAuth = field.NewInt32(table, "meta_requires_auth")
	s.MetaIcon = field.NewString(table, "meta_icon")
	s.MetaLocalIcon = field.NewString(table, "meta_local_icon")
	s.MetaI18nKey = field.NewString(table, "meta_i18n_key")
	s.MetaHref = field.NewString(table, "meta_href")
	s.MetaKeepAlive = field.NewInt32(table, "meta_keep_alive")
	s.MetaTitle = field.NewString(table, "meta_title")
	s.MetaActiveMenu = field.NewString(table, "meta_active_menu")
	s.MetaMultiTab = field.NewInt32(table, "meta_multi_tab")
	s.MetaFixedInTab = field.NewInt32(table, "meta_fixed_in_tab")
	s.MetaQuery = field.NewString(table, "meta_query")
	s.Version = field.NewInt32(table, "version")
	s.SoftDeleteTag = field.NewInt32(table, "soft_delete_tag")
	s.UpdateTime = field.NewTime(table, "update_time")
	s.UpdateUID = field.NewInt32(table, "update_uid")
	s.CreateUID = field.NewInt32(table, "create_uid")
	s.CreateBy = field.NewString(table, "create_by")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateBy = field.NewString(table, "update_by")

	s.fillFieldMap()

	return s
}

func (s *sysMenu) WithContext(ctx context.Context) *sysMenuDo { return s.sysMenuDo.WithContext(ctx) }

func (s sysMenu) TableName() string { return s.sysMenuDo.TableName() }

func (s sysMenu) Alias() string { return s.sysMenuDo.Alias() }

func (s sysMenu) Columns(cols ...field.Expr) gen.Columns { return s.sysMenuDo.Columns(cols...) }

func (s *sysMenu) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysMenu) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 31)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["path"] = s.Path
	s.fieldMap["redirect"] = s.Redirect
	s.fieldMap["parent_id"] = s.ParentID
	s.fieldMap["component"] = s.Component
	s.fieldMap["props"] = s.Props
	s.fieldMap["status"] = s.Status
	s.fieldMap["meta_icon_type"] = s.MetaIconType
	s.fieldMap["meta_order"] = s.MetaOrder
	s.fieldMap["meta_constant"] = s.MetaConstant
	s.fieldMap["meta_hide_in_menu"] = s.MetaHideInMenu
	s.fieldMap["meta_requires_auth"] = s.MetaRequiresAuth
	s.fieldMap["meta_icon"] = s.MetaIcon
	s.fieldMap["meta_local_icon"] = s.MetaLocalIcon
	s.fieldMap["meta_i18n_key"] = s.MetaI18nKey
	s.fieldMap["meta_href"] = s.MetaHref
	s.fieldMap["meta_keep_alive"] = s.MetaKeepAlive
	s.fieldMap["meta_title"] = s.MetaTitle
	s.fieldMap["meta_active_menu"] = s.MetaActiveMenu
	s.fieldMap["meta_multi_tab"] = s.MetaMultiTab
	s.fieldMap["meta_fixed_in_tab"] = s.MetaFixedInTab
	s.fieldMap["meta_query"] = s.MetaQuery
	s.fieldMap["version"] = s.Version
	s.fieldMap["soft_delete_tag"] = s.SoftDeleteTag
	s.fieldMap["update_time"] = s.UpdateTime
	s.fieldMap["update_uid"] = s.UpdateUID
	s.fieldMap["create_uid"] = s.CreateUID
	s.fieldMap["create_by"] = s.CreateBy
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_by"] = s.UpdateBy
}

func (s sysMenu) clone(db *gorm.DB) sysMenu {
	s.sysMenuDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysMenu) replaceDB(db *gorm.DB) sysMenu {
	s.sysMenuDo.ReplaceDB(db)
	return s
}

type sysMenuDo struct{ gen.DO }

func (s sysMenuDo) Debug() *sysMenuDo {
	return s.withDO(s.DO.Debug())
}

func (s sysMenuDo) WithContext(ctx context.Context) *sysMenuDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysMenuDo) ReadDB() *sysMenuDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysMenuDo) WriteDB() *sysMenuDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysMenuDo) Session(config *gorm.Session) *sysMenuDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysMenuDo) Clauses(conds ...clause.Expression) *sysMenuDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysMenuDo) Returning(value interface{}, columns ...string) *sysMenuDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysMenuDo) Not(conds ...gen.Condition) *sysMenuDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysMenuDo) Or(conds ...gen.Condition) *sysMenuDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysMenuDo) Select(conds ...field.Expr) *sysMenuDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysMenuDo) Where(conds ...gen.Condition) *sysMenuDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysMenuDo) Order(conds ...field.Expr) *sysMenuDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysMenuDo) Distinct(cols ...field.Expr) *sysMenuDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysMenuDo) Omit(cols ...field.Expr) *sysMenuDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysMenuDo) Join(table schema.Tabler, on ...field.Expr) *sysMenuDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysMenuDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysMenuDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysMenuDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysMenuDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysMenuDo) Group(cols ...field.Expr) *sysMenuDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysMenuDo) Having(conds ...gen.Condition) *sysMenuDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysMenuDo) Limit(limit int) *sysMenuDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysMenuDo) Offset(offset int) *sysMenuDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysMenuDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysMenuDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysMenuDo) Unscoped() *sysMenuDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysMenuDo) Create(values ...*model.SysMenu) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysMenuDo) CreateInBatches(values []*model.SysMenu, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysMenuDo) Save(values ...*model.SysMenu) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysMenuDo) First() (*model.SysMenu, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysMenu), nil
	}
}

func (s sysMenuDo) Take() (*model.SysMenu, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysMenu), nil
	}
}

func (s sysMenuDo) Last() (*model.SysMenu, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysMenu), nil
	}
}

func (s sysMenuDo) Find() ([]*model.SysMenu, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysMenu), err
}

func (s sysMenuDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysMenu, err error) {
	buf := make([]*model.SysMenu, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysMenuDo) FindInBatches(result *[]*model.SysMenu, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysMenuDo) Attrs(attrs ...field.AssignExpr) *sysMenuDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysMenuDo) Assign(attrs ...field.AssignExpr) *sysMenuDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysMenuDo) Joins(fields ...field.RelationField) *sysMenuDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysMenuDo) Preload(fields ...field.RelationField) *sysMenuDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysMenuDo) FirstOrInit() (*model.SysMenu, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysMenu), nil
	}
}

func (s sysMenuDo) FirstOrCreate() (*model.SysMenu, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysMenu), nil
	}
}

func (s sysMenuDo) FindByPage(offset int, limit int) (result []*model.SysMenu, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysMenuDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysMenuDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysMenuDo) Delete(models ...*model.SysMenu) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysMenuDo) withDO(do gen.Dao) *sysMenuDo {
	s.DO = *do.(*gen.DO)
	return s
}
