// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"xcore/dao/model"
)

func newSysOauth2Bind(db *gorm.DB, opts ...gen.DOOption) sysOauth2Bind {
	_sysOauth2Bind := sysOauth2Bind{}

	_sysOauth2Bind.sysOauth2BindDo.UseDB(db, opts...)
	_sysOauth2Bind.sysOauth2BindDo.UseModel(&model.SysOauth2Bind{})

	tableName := _sysOauth2Bind.sysOauth2BindDo.TableName()
	_sysOauth2Bind.ALL = field.NewAsterisk(tableName)
	_sysOauth2Bind.UserUID = field.NewString(tableName, "user_uid")
	_sysOauth2Bind.PlatformCode = field.NewString(tableName, "platform_code")
	_sysOauth2Bind.PlatformUID = field.NewString(tableName, "platform_uid")

	_sysOauth2Bind.fillFieldMap()

	return _sysOauth2Bind
}

type sysOauth2Bind struct {
	sysOauth2BindDo

	ALL          field.Asterisk
	UserUID      field.String // 本系统用户的ID
	PlatformCode field.String // 三方平台代码
	PlatformUID  field.String // 三方平台用户ID

	fieldMap map[string]field.Expr
}

func (s sysOauth2Bind) Table(newTableName string) *sysOauth2Bind {
	s.sysOauth2BindDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysOauth2Bind) As(alias string) *sysOauth2Bind {
	s.sysOauth2BindDo.DO = *(s.sysOauth2BindDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysOauth2Bind) updateTableName(table string) *sysOauth2Bind {
	s.ALL = field.NewAsterisk(table)
	s.UserUID = field.NewString(table, "user_uid")
	s.PlatformCode = field.NewString(table, "platform_code")
	s.PlatformUID = field.NewString(table, "platform_uid")

	s.fillFieldMap()

	return s
}

func (s *sysOauth2Bind) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysOauth2Bind) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 3)
	s.fieldMap["user_uid"] = s.UserUID
	s.fieldMap["platform_code"] = s.PlatformCode
	s.fieldMap["platform_uid"] = s.PlatformUID
}

func (s sysOauth2Bind) clone(db *gorm.DB) sysOauth2Bind {
	s.sysOauth2BindDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysOauth2Bind) replaceDB(db *gorm.DB) sysOauth2Bind {
	s.sysOauth2BindDo.ReplaceDB(db)
	return s
}

type sysOauth2BindDo struct{ gen.DO }

type ISysOauth2BindDo interface {
	gen.SubQuery
	Debug() ISysOauth2BindDo
	WithContext(ctx context.Context) ISysOauth2BindDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysOauth2BindDo
	WriteDB() ISysOauth2BindDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysOauth2BindDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysOauth2BindDo
	Not(conds ...gen.Condition) ISysOauth2BindDo
	Or(conds ...gen.Condition) ISysOauth2BindDo
	Select(conds ...field.Expr) ISysOauth2BindDo
	Where(conds ...gen.Condition) ISysOauth2BindDo
	Order(conds ...field.Expr) ISysOauth2BindDo
	Distinct(cols ...field.Expr) ISysOauth2BindDo
	Omit(cols ...field.Expr) ISysOauth2BindDo
	Join(table schema.Tabler, on ...field.Expr) ISysOauth2BindDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysOauth2BindDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysOauth2BindDo
	Group(cols ...field.Expr) ISysOauth2BindDo
	Having(conds ...gen.Condition) ISysOauth2BindDo
	Limit(limit int) ISysOauth2BindDo
	Offset(offset int) ISysOauth2BindDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysOauth2BindDo
	Unscoped() ISysOauth2BindDo
	Create(values ...*model.SysOauth2Bind) error
	CreateInBatches(values []*model.SysOauth2Bind, batchSize int) error
	Save(values ...*model.SysOauth2Bind) error
	First() (*model.SysOauth2Bind, error)
	Take() (*model.SysOauth2Bind, error)
	Last() (*model.SysOauth2Bind, error)
	Find() ([]*model.SysOauth2Bind, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysOauth2Bind, err error)
	FindInBatches(result *[]*model.SysOauth2Bind, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysOauth2Bind) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysOauth2BindDo
	Assign(attrs ...field.AssignExpr) ISysOauth2BindDo
	Joins(fields ...field.RelationField) ISysOauth2BindDo
	Preload(fields ...field.RelationField) ISysOauth2BindDo
	FirstOrInit() (*model.SysOauth2Bind, error)
	FirstOrCreate() (*model.SysOauth2Bind, error)
	FindByPage(offset int, limit int) (result []*model.SysOauth2Bind, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysOauth2BindDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysOauth2BindDo) Debug() ISysOauth2BindDo {
	return s.withDO(s.DO.Debug())
}

func (s sysOauth2BindDo) WithContext(ctx context.Context) ISysOauth2BindDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysOauth2BindDo) ReadDB() ISysOauth2BindDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysOauth2BindDo) WriteDB() ISysOauth2BindDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysOauth2BindDo) Session(config *gorm.Session) ISysOauth2BindDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysOauth2BindDo) Clauses(conds ...clause.Expression) ISysOauth2BindDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysOauth2BindDo) Returning(value interface{}, columns ...string) ISysOauth2BindDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysOauth2BindDo) Not(conds ...gen.Condition) ISysOauth2BindDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysOauth2BindDo) Or(conds ...gen.Condition) ISysOauth2BindDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysOauth2BindDo) Select(conds ...field.Expr) ISysOauth2BindDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysOauth2BindDo) Where(conds ...gen.Condition) ISysOauth2BindDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysOauth2BindDo) Order(conds ...field.Expr) ISysOauth2BindDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysOauth2BindDo) Distinct(cols ...field.Expr) ISysOauth2BindDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysOauth2BindDo) Omit(cols ...field.Expr) ISysOauth2BindDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysOauth2BindDo) Join(table schema.Tabler, on ...field.Expr) ISysOauth2BindDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysOauth2BindDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysOauth2BindDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysOauth2BindDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysOauth2BindDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysOauth2BindDo) Group(cols ...field.Expr) ISysOauth2BindDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysOauth2BindDo) Having(conds ...gen.Condition) ISysOauth2BindDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysOauth2BindDo) Limit(limit int) ISysOauth2BindDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysOauth2BindDo) Offset(offset int) ISysOauth2BindDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysOauth2BindDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysOauth2BindDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysOauth2BindDo) Unscoped() ISysOauth2BindDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysOauth2BindDo) Create(values ...*model.SysOauth2Bind) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysOauth2BindDo) CreateInBatches(values []*model.SysOauth2Bind, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysOauth2BindDo) Save(values ...*model.SysOauth2Bind) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysOauth2BindDo) First() (*model.SysOauth2Bind, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOauth2Bind), nil
	}
}

func (s sysOauth2BindDo) Take() (*model.SysOauth2Bind, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOauth2Bind), nil
	}
}

func (s sysOauth2BindDo) Last() (*model.SysOauth2Bind, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOauth2Bind), nil
	}
}

func (s sysOauth2BindDo) Find() ([]*model.SysOauth2Bind, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysOauth2Bind), err
}

func (s sysOauth2BindDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysOauth2Bind, err error) {
	buf := make([]*model.SysOauth2Bind, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysOauth2BindDo) FindInBatches(result *[]*model.SysOauth2Bind, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysOauth2BindDo) Attrs(attrs ...field.AssignExpr) ISysOauth2BindDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysOauth2BindDo) Assign(attrs ...field.AssignExpr) ISysOauth2BindDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysOauth2BindDo) Joins(fields ...field.RelationField) ISysOauth2BindDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysOauth2BindDo) Preload(fields ...field.RelationField) ISysOauth2BindDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysOauth2BindDo) FirstOrInit() (*model.SysOauth2Bind, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOauth2Bind), nil
	}
}

func (s sysOauth2BindDo) FirstOrCreate() (*model.SysOauth2Bind, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOauth2Bind), nil
	}
}

func (s sysOauth2BindDo) FindByPage(offset int, limit int) (result []*model.SysOauth2Bind, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysOauth2BindDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysOauth2BindDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysOauth2BindDo) Delete(models ...*model.SysOauth2Bind) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysOauth2BindDo) withDO(do gen.Dao) *sysOauth2BindDo {
	s.DO = *do.(*gen.DO)
	return s
}
