// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"xadmin/soybean/dao/model"
)

func newSysGenTable(db *gorm.DB, opts ...gen.DOOption) sysGenTable {
	_sysGenTable := sysGenTable{}

	_sysGenTable.sysGenTableDo.UseDB(db, opts...)
	_sysGenTable.sysGenTableDo.UseModel(&model.SysGenTable{})

	tableName := _sysGenTable.sysGenTableDo.TableName()
	_sysGenTable.ALL = field.NewAsterisk(tableName)
	_sysGenTable.UID = field.NewString(tableName, "uid")
	_sysGenTable.TableName_ = field.NewString(tableName, "table_name")
	_sysGenTable.TableComment = field.NewString(tableName, "table_comment")
	_sysGenTable.AuthorName = field.NewString(tableName, "author_name")
	_sysGenTable.LowUpName = field.NewString(tableName, "low_up_name")
	_sysGenTable.UpUpName = field.NewString(tableName, "up_up_name")
	_sysGenTable.RelativePath = field.NewString(tableName, "relative_path")
	_sysGenTable.IsCheckToken = field.NewInt32(tableName, "is_check_token")
	_sysGenTable.IsCheckAuth = field.NewInt32(tableName, "is_check_auth")
	_sysGenTable.IsCreateLog = field.NewInt32(tableName, "is_create_log")
	_sysGenTable.Remarks = field.NewString(tableName, "remarks")
	_sysGenTable.Version = field.NewInt32(tableName, "version")
	_sysGenTable.CreateUID = field.NewInt32(tableName, "create_uid")
	_sysGenTable.CreateBy = field.NewString(tableName, "create_by")
	_sysGenTable.CreateTime = field.NewTime(tableName, "create_time")
	_sysGenTable.UpdateTime = field.NewTime(tableName, "update_time")
	_sysGenTable.UpdateUID = field.NewInt32(tableName, "update_uid")
	_sysGenTable.SoftDeleteTag = field.NewInt32(tableName, "soft_delete_tag")
	_sysGenTable.UpdateBy = field.NewString(tableName, "update_by")

	_sysGenTable.fillFieldMap()

	return _sysGenTable
}

type sysGenTable struct {
	sysGenTableDo

	ALL           field.Asterisk
	UID           field.String // 主键
	TableName_    field.String // 表名称
	TableComment  field.String // 表描述
	AuthorName    field.String // 作者的名称
	LowUpName     field.String // 实体的名称
	UpUpName      field.String // 生成模块名
	RelativePath  field.String // 相对路径
	IsCheckToken  field.Int32  // 需要检测是否有Token
	IsCheckAuth   field.Int32  // 是否鉴权
	IsCreateLog   field.Int32  // 是否创建日志
	Remarks       field.String // 备注信息
	Version       field.Int32  // 乐观锁
	CreateUID     field.Int32  // 创建者uid
	CreateBy      field.String // 创建者
	CreateTime    field.Time   // 创建时间
	UpdateTime    field.Time   // 更新时间
	UpdateUID     field.Int32  // 更新者uid
	SoftDeleteTag field.Int32  // 软删除标记
	UpdateBy      field.String // 更新者

	fieldMap map[string]field.Expr
}

func (s sysGenTable) Table(newTableName string) *sysGenTable {
	s.sysGenTableDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysGenTable) As(alias string) *sysGenTable {
	s.sysGenTableDo.DO = *(s.sysGenTableDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysGenTable) updateTableName(table string) *sysGenTable {
	s.ALL = field.NewAsterisk(table)
	s.UID = field.NewString(table, "uid")
	s.TableName_ = field.NewString(table, "table_name")
	s.TableComment = field.NewString(table, "table_comment")
	s.AuthorName = field.NewString(table, "author_name")
	s.LowUpName = field.NewString(table, "low_up_name")
	s.UpUpName = field.NewString(table, "up_up_name")
	s.RelativePath = field.NewString(table, "relative_path")
	s.IsCheckToken = field.NewInt32(table, "is_check_token")
	s.IsCheckAuth = field.NewInt32(table, "is_check_auth")
	s.IsCreateLog = field.NewInt32(table, "is_create_log")
	s.Remarks = field.NewString(table, "remarks")
	s.Version = field.NewInt32(table, "version")
	s.CreateUID = field.NewInt32(table, "create_uid")
	s.CreateBy = field.NewString(table, "create_by")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")
	s.UpdateUID = field.NewInt32(table, "update_uid")
	s.SoftDeleteTag = field.NewInt32(table, "soft_delete_tag")
	s.UpdateBy = field.NewString(table, "update_by")

	s.fillFieldMap()

	return s
}

func (s *sysGenTable) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysGenTable) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 19)
	s.fieldMap["uid"] = s.UID
	s.fieldMap["table_name"] = s.TableName_
	s.fieldMap["table_comment"] = s.TableComment
	s.fieldMap["author_name"] = s.AuthorName
	s.fieldMap["low_up_name"] = s.LowUpName
	s.fieldMap["up_up_name"] = s.UpUpName
	s.fieldMap["relative_path"] = s.RelativePath
	s.fieldMap["is_check_token"] = s.IsCheckToken
	s.fieldMap["is_check_auth"] = s.IsCheckAuth
	s.fieldMap["is_create_log"] = s.IsCreateLog
	s.fieldMap["remarks"] = s.Remarks
	s.fieldMap["version"] = s.Version
	s.fieldMap["create_uid"] = s.CreateUID
	s.fieldMap["create_by"] = s.CreateBy
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
	s.fieldMap["update_uid"] = s.UpdateUID
	s.fieldMap["soft_delete_tag"] = s.SoftDeleteTag
	s.fieldMap["update_by"] = s.UpdateBy
}

func (s sysGenTable) clone(db *gorm.DB) sysGenTable {
	s.sysGenTableDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysGenTable) replaceDB(db *gorm.DB) sysGenTable {
	s.sysGenTableDo.ReplaceDB(db)
	return s
}

type sysGenTableDo struct{ gen.DO }

type ISysGenTableDo interface {
	gen.SubQuery
	Debug() ISysGenTableDo
	WithContext(ctx context.Context) ISysGenTableDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysGenTableDo
	WriteDB() ISysGenTableDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysGenTableDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysGenTableDo
	Not(conds ...gen.Condition) ISysGenTableDo
	Or(conds ...gen.Condition) ISysGenTableDo
	Select(conds ...field.Expr) ISysGenTableDo
	Where(conds ...gen.Condition) ISysGenTableDo
	Order(conds ...field.Expr) ISysGenTableDo
	Distinct(cols ...field.Expr) ISysGenTableDo
	Omit(cols ...field.Expr) ISysGenTableDo
	Join(table schema.Tabler, on ...field.Expr) ISysGenTableDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysGenTableDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysGenTableDo
	Group(cols ...field.Expr) ISysGenTableDo
	Having(conds ...gen.Condition) ISysGenTableDo
	Limit(limit int) ISysGenTableDo
	Offset(offset int) ISysGenTableDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysGenTableDo
	Unscoped() ISysGenTableDo
	Create(values ...*model.SysGenTable) error
	CreateInBatches(values []*model.SysGenTable, batchSize int) error
	Save(values ...*model.SysGenTable) error
	First() (*model.SysGenTable, error)
	Take() (*model.SysGenTable, error)
	Last() (*model.SysGenTable, error)
	Find() ([]*model.SysGenTable, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysGenTable, err error)
	FindInBatches(result *[]*model.SysGenTable, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysGenTable) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysGenTableDo
	Assign(attrs ...field.AssignExpr) ISysGenTableDo
	Joins(fields ...field.RelationField) ISysGenTableDo
	Preload(fields ...field.RelationField) ISysGenTableDo
	FirstOrInit() (*model.SysGenTable, error)
	FirstOrCreate() (*model.SysGenTable, error)
	FindByPage(offset int, limit int) (result []*model.SysGenTable, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysGenTableDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysGenTableDo) Debug() ISysGenTableDo {
	return s.withDO(s.DO.Debug())
}

func (s sysGenTableDo) WithContext(ctx context.Context) ISysGenTableDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysGenTableDo) ReadDB() ISysGenTableDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysGenTableDo) WriteDB() ISysGenTableDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysGenTableDo) Session(config *gorm.Session) ISysGenTableDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysGenTableDo) Clauses(conds ...clause.Expression) ISysGenTableDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysGenTableDo) Returning(value interface{}, columns ...string) ISysGenTableDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysGenTableDo) Not(conds ...gen.Condition) ISysGenTableDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysGenTableDo) Or(conds ...gen.Condition) ISysGenTableDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysGenTableDo) Select(conds ...field.Expr) ISysGenTableDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysGenTableDo) Where(conds ...gen.Condition) ISysGenTableDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysGenTableDo) Order(conds ...field.Expr) ISysGenTableDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysGenTableDo) Distinct(cols ...field.Expr) ISysGenTableDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysGenTableDo) Omit(cols ...field.Expr) ISysGenTableDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysGenTableDo) Join(table schema.Tabler, on ...field.Expr) ISysGenTableDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysGenTableDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysGenTableDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysGenTableDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysGenTableDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysGenTableDo) Group(cols ...field.Expr) ISysGenTableDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysGenTableDo) Having(conds ...gen.Condition) ISysGenTableDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysGenTableDo) Limit(limit int) ISysGenTableDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysGenTableDo) Offset(offset int) ISysGenTableDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysGenTableDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysGenTableDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysGenTableDo) Unscoped() ISysGenTableDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysGenTableDo) Create(values ...*model.SysGenTable) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysGenTableDo) CreateInBatches(values []*model.SysGenTable, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysGenTableDo) Save(values ...*model.SysGenTable) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysGenTableDo) First() (*model.SysGenTable, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysGenTable), nil
	}
}

func (s sysGenTableDo) Take() (*model.SysGenTable, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysGenTable), nil
	}
}

func (s sysGenTableDo) Last() (*model.SysGenTable, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysGenTable), nil
	}
}

func (s sysGenTableDo) Find() ([]*model.SysGenTable, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysGenTable), err
}

func (s sysGenTableDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysGenTable, err error) {
	buf := make([]*model.SysGenTable, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysGenTableDo) FindInBatches(result *[]*model.SysGenTable, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysGenTableDo) Attrs(attrs ...field.AssignExpr) ISysGenTableDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysGenTableDo) Assign(attrs ...field.AssignExpr) ISysGenTableDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysGenTableDo) Joins(fields ...field.RelationField) ISysGenTableDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysGenTableDo) Preload(fields ...field.RelationField) ISysGenTableDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysGenTableDo) FirstOrInit() (*model.SysGenTable, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysGenTable), nil
	}
}

func (s sysGenTableDo) FirstOrCreate() (*model.SysGenTable, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysGenTable), nil
	}
}

func (s sysGenTableDo) FindByPage(offset int, limit int) (result []*model.SysGenTable, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysGenTableDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysGenTableDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysGenTableDo) Delete(models ...*model.SysGenTable) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysGenTableDo) withDO(do gen.Dao) *sysGenTableDo {
	s.DO = *do.(*gen.DO)
	return s
}
