// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	SysAPI            *sysAPI
	SysCron           *sysCron
	SysDepartment     *sysDepartment
	SysDictDatum      *sysDictDatum
	SysDictType       *sysDictType
	SysGenTable       *sysGenTable
	SysGenTableColumn *sysGenTableColumn
	SysMenu           *sysMenu
	SysOauth2Bind     *sysOauth2Bind
	SysRole           *sysRole
	SysUser           *sysUser
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	SysAPI = &Q.SysAPI
	SysCron = &Q.SysCron
	SysDepartment = &Q.SysDepartment
	SysDictDatum = &Q.SysDictDatum
	SysDictType = &Q.SysDictType
	SysGenTable = &Q.SysGenTable
	SysGenTableColumn = &Q.SysGenTableColumn
	SysMenu = &Q.SysMenu
	SysOauth2Bind = &Q.SysOauth2Bind
	SysRole = &Q.SysRole
	SysUser = &Q.SysUser
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		SysAPI:            newSysAPI(db, opts...),
		SysCron:           newSysCron(db, opts...),
		SysDepartment:     newSysDepartment(db, opts...),
		SysDictDatum:      newSysDictDatum(db, opts...),
		SysDictType:       newSysDictType(db, opts...),
		SysGenTable:       newSysGenTable(db, opts...),
		SysGenTableColumn: newSysGenTableColumn(db, opts...),
		SysMenu:           newSysMenu(db, opts...),
		SysOauth2Bind:     newSysOauth2Bind(db, opts...),
		SysRole:           newSysRole(db, opts...),
		SysUser:           newSysUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	SysAPI            sysAPI
	SysCron           sysCron
	SysDepartment     sysDepartment
	SysDictDatum      sysDictDatum
	SysDictType       sysDictType
	SysGenTable       sysGenTable
	SysGenTableColumn sysGenTableColumn
	SysMenu           sysMenu
	SysOauth2Bind     sysOauth2Bind
	SysRole           sysRole
	SysUser           sysUser
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		SysAPI:            q.SysAPI.clone(db),
		SysCron:           q.SysCron.clone(db),
		SysDepartment:     q.SysDepartment.clone(db),
		SysDictDatum:      q.SysDictDatum.clone(db),
		SysDictType:       q.SysDictType.clone(db),
		SysGenTable:       q.SysGenTable.clone(db),
		SysGenTableColumn: q.SysGenTableColumn.clone(db),
		SysMenu:           q.SysMenu.clone(db),
		SysOauth2Bind:     q.SysOauth2Bind.clone(db),
		SysRole:           q.SysRole.clone(db),
		SysUser:           q.SysUser.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		SysAPI:            q.SysAPI.replaceDB(db),
		SysCron:           q.SysCron.replaceDB(db),
		SysDepartment:     q.SysDepartment.replaceDB(db),
		SysDictDatum:      q.SysDictDatum.replaceDB(db),
		SysDictType:       q.SysDictType.replaceDB(db),
		SysGenTable:       q.SysGenTable.replaceDB(db),
		SysGenTableColumn: q.SysGenTableColumn.replaceDB(db),
		SysMenu:           q.SysMenu.replaceDB(db),
		SysOauth2Bind:     q.SysOauth2Bind.replaceDB(db),
		SysRole:           q.SysRole.replaceDB(db),
		SysUser:           q.SysUser.replaceDB(db),
	}
}

type queryCtx struct {
	SysAPI            ISysAPIDo
	SysCron           ISysCronDo
	SysDepartment     ISysDepartmentDo
	SysDictDatum      ISysDictDatumDo
	SysDictType       ISysDictTypeDo
	SysGenTable       ISysGenTableDo
	SysGenTableColumn ISysGenTableColumnDo
	SysMenu           ISysMenuDo
	SysOauth2Bind     ISysOauth2BindDo
	SysRole           ISysRoleDo
	SysUser           ISysUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		SysAPI:            q.SysAPI.WithContext(ctx),
		SysCron:           q.SysCron.WithContext(ctx),
		SysDepartment:     q.SysDepartment.WithContext(ctx),
		SysDictDatum:      q.SysDictDatum.WithContext(ctx),
		SysDictType:       q.SysDictType.WithContext(ctx),
		SysGenTable:       q.SysGenTable.WithContext(ctx),
		SysGenTableColumn: q.SysGenTableColumn.WithContext(ctx),
		SysMenu:           q.SysMenu.WithContext(ctx),
		SysOauth2Bind:     q.SysOauth2Bind.WithContext(ctx),
		SysRole:           q.SysRole.WithContext(ctx),
		SysUser:           q.SysUser.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
