// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"xadmin/soybean/dao/model"
)

func newSysCron(db *gorm.DB, opts ...gen.DOOption) sysCron {
	_sysCron := sysCron{}

	_sysCron.sysCronDo.UseDB(db, opts...)
	_sysCron.sysCronDo.UseModel(&model.SysCron{})

	tableName := _sysCron.sysCronDo.TableName()
	_sysCron.ALL = field.NewAsterisk(tableName)
	_sysCron.Key = field.NewString(tableName, "key")
	_sysCron.Description = field.NewString(tableName, "description")
	_sysCron.Schedule = field.NewString(tableName, "schedule")
	_sysCron.Status = field.NewString(tableName, "status")
	_sysCron.Arguments = field.NewString(tableName, "arguments")
	_sysCron.ArgumentsType = field.NewString(tableName, "arguments_type")

	_sysCron.fillFieldMap()

	return _sysCron
}

type sysCron struct {
	sysCronDo

	ALL           field.Asterisk
	Key           field.String // 唯一键值
	Description   field.String // 描述
	Schedule      field.String // cron表达式
	Status        field.String // 状态
	Arguments     field.String // 参数
	ArgumentsType field.String // 参数类型

	fieldMap map[string]field.Expr
}

func (s sysCron) Table(newTableName string) *sysCron {
	s.sysCronDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysCron) As(alias string) *sysCron {
	s.sysCronDo.DO = *(s.sysCronDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysCron) updateTableName(table string) *sysCron {
	s.ALL = field.NewAsterisk(table)
	s.Key = field.NewString(table, "key")
	s.Description = field.NewString(table, "description")
	s.Schedule = field.NewString(table, "schedule")
	s.Status = field.NewString(table, "status")
	s.Arguments = field.NewString(table, "arguments")
	s.ArgumentsType = field.NewString(table, "arguments_type")

	s.fillFieldMap()

	return s
}

func (s *sysCron) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysCron) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["key"] = s.Key
	s.fieldMap["description"] = s.Description
	s.fieldMap["schedule"] = s.Schedule
	s.fieldMap["status"] = s.Status
	s.fieldMap["arguments"] = s.Arguments
	s.fieldMap["arguments_type"] = s.ArgumentsType
}

func (s sysCron) clone(db *gorm.DB) sysCron {
	s.sysCronDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysCron) replaceDB(db *gorm.DB) sysCron {
	s.sysCronDo.ReplaceDB(db)
	return s
}

type sysCronDo struct{ gen.DO }

type ISysCronDo interface {
	gen.SubQuery
	Debug() ISysCronDo
	WithContext(ctx context.Context) ISysCronDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysCronDo
	WriteDB() ISysCronDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysCronDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysCronDo
	Not(conds ...gen.Condition) ISysCronDo
	Or(conds ...gen.Condition) ISysCronDo
	Select(conds ...field.Expr) ISysCronDo
	Where(conds ...gen.Condition) ISysCronDo
	Order(conds ...field.Expr) ISysCronDo
	Distinct(cols ...field.Expr) ISysCronDo
	Omit(cols ...field.Expr) ISysCronDo
	Join(table schema.Tabler, on ...field.Expr) ISysCronDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysCronDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysCronDo
	Group(cols ...field.Expr) ISysCronDo
	Having(conds ...gen.Condition) ISysCronDo
	Limit(limit int) ISysCronDo
	Offset(offset int) ISysCronDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysCronDo
	Unscoped() ISysCronDo
	Create(values ...*model.SysCron) error
	CreateInBatches(values []*model.SysCron, batchSize int) error
	Save(values ...*model.SysCron) error
	First() (*model.SysCron, error)
	Take() (*model.SysCron, error)
	Last() (*model.SysCron, error)
	Find() ([]*model.SysCron, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysCron, err error)
	FindInBatches(result *[]*model.SysCron, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysCron) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysCronDo
	Assign(attrs ...field.AssignExpr) ISysCronDo
	Joins(fields ...field.RelationField) ISysCronDo
	Preload(fields ...field.RelationField) ISysCronDo
	FirstOrInit() (*model.SysCron, error)
	FirstOrCreate() (*model.SysCron, error)
	FindByPage(offset int, limit int) (result []*model.SysCron, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysCronDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysCronDo) Debug() ISysCronDo {
	return s.withDO(s.DO.Debug())
}

func (s sysCronDo) WithContext(ctx context.Context) ISysCronDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysCronDo) ReadDB() ISysCronDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysCronDo) WriteDB() ISysCronDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysCronDo) Session(config *gorm.Session) ISysCronDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysCronDo) Clauses(conds ...clause.Expression) ISysCronDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysCronDo) Returning(value interface{}, columns ...string) ISysCronDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysCronDo) Not(conds ...gen.Condition) ISysCronDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysCronDo) Or(conds ...gen.Condition) ISysCronDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysCronDo) Select(conds ...field.Expr) ISysCronDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysCronDo) Where(conds ...gen.Condition) ISysCronDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysCronDo) Order(conds ...field.Expr) ISysCronDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysCronDo) Distinct(cols ...field.Expr) ISysCronDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysCronDo) Omit(cols ...field.Expr) ISysCronDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysCronDo) Join(table schema.Tabler, on ...field.Expr) ISysCronDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysCronDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysCronDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysCronDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysCronDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysCronDo) Group(cols ...field.Expr) ISysCronDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysCronDo) Having(conds ...gen.Condition) ISysCronDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysCronDo) Limit(limit int) ISysCronDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysCronDo) Offset(offset int) ISysCronDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysCronDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysCronDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysCronDo) Unscoped() ISysCronDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysCronDo) Create(values ...*model.SysCron) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysCronDo) CreateInBatches(values []*model.SysCron, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysCronDo) Save(values ...*model.SysCron) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysCronDo) First() (*model.SysCron, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysCron), nil
	}
}

func (s sysCronDo) Take() (*model.SysCron, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysCron), nil
	}
}

func (s sysCronDo) Last() (*model.SysCron, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysCron), nil
	}
}

func (s sysCronDo) Find() ([]*model.SysCron, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysCron), err
}

func (s sysCronDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysCron, err error) {
	buf := make([]*model.SysCron, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysCronDo) FindInBatches(result *[]*model.SysCron, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysCronDo) Attrs(attrs ...field.AssignExpr) ISysCronDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysCronDo) Assign(attrs ...field.AssignExpr) ISysCronDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysCronDo) Joins(fields ...field.RelationField) ISysCronDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysCronDo) Preload(fields ...field.RelationField) ISysCronDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysCronDo) FirstOrInit() (*model.SysCron, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysCron), nil
	}
}

func (s sysCronDo) FirstOrCreate() (*model.SysCron, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysCron), nil
	}
}

func (s sysCronDo) FindByPage(offset int, limit int) (result []*model.SysCron, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysCronDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysCronDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysCronDo) Delete(models ...*model.SysCron) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysCronDo) withDO(do gen.Dao) *sysCronDo {
	s.DO = *do.(*gen.DO)
	return s
}
