/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";
import ProjectLayout from "@/layouts/project-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
  project: ProjectLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about: () => import("@/views/about/index.vue"),
  "code-gen_column": () => import("@/views/code-gen/column/[name].vue"),
  "code-gen_table": () => import("@/views/code-gen/table/index.vue"),
  cron: () => import("@/views/cron/index.vue"),
  dict_data: () => import("@/views/dict/data/[code].vue"),
  dict_type: () => import("@/views/dict/type/index.vue"),
  "function_hide-child_one": () => import("@/views/function/hide-child/one/index.vue"),
  "function_hide-child_three": () => import("@/views/function/hide-child/three/index.vue"),
  "function_hide-child_two": () => import("@/views/function/hide-child/two/index.vue"),
  "function_multi-tab": () => import("@/views/function/multi-tab/index.vue"),
  function_request: () => import("@/views/function/request/index.vue"),
  "function_super-page": () => import("@/views/function/super-page/index.vue"),
  function_tab: () => import("@/views/function/tab/index.vue"),
  "function_toggle-auth": () => import("@/views/function/toggle-auth/index.vue"),
  home: () => import("@/views/home/index.vue"),
  logger_file: () => import("@/views/logger/file/index.vue"),
  logger_info: () => import("@/views/logger/info/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  "project-list": () => import("@/views/project-list/index.vue"),
  projects_document_api: () => import("@/views/projects/document/api/index.vue"),
  projects_document_files: () => import("@/views/projects/document/files/index.vue"),
  projects_document_knowledge: () => import("@/views/projects/document/knowledge/index.vue"),
  projects_document_wiki: () => import("@/views/projects/document/wiki/index.vue"),
  projects_overview: () => import("@/views/projects/overview/index.vue"),
  projects_repository: () => import("@/views/projects/repository/index.vue"),
  projects_synergy: () => import("@/views/projects/synergy/index.vue"),
  projects_test_overview: () => import("@/views/projects/test/overview/index.vue"),
  projects_test_plan: () => import("@/views/projects/test/plan/index.vue"),
  projects_test_report: () => import("@/views/projects/test/report/index.vue"),
  "projects_test_use-case": () => import("@/views/projects/test/use-case/index.vue"),
  "test-page_page-one": () => import("@/views/test-page/page-one/index.vue"),
  "test-page_page-two": () => import("@/views/test-page/page-two/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
