/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about'
    }
  },
  {
    name: 'code-gen',
    path: '/code-gen',
    component: 'layout.base',
    meta: {
      title: 'code-gen',
      i18nKey: 'route.code-gen'
    },
    children: [
      {
        name: 'code-gen_column',
        path: '/code-gen/column/:name',
        component: 'view.code-gen_column',
        meta: {
          title: 'code-gen_column',
          i18nKey: 'route.code-gen_column'
        }
      },
      {
        name: 'code-gen_table',
        path: '/code-gen/table',
        component: 'view.code-gen_table',
        meta: {
          title: 'code-gen_table',
          i18nKey: 'route.code-gen_table'
        }
      }
    ]
  },
  {
    name: 'cron',
    path: '/cron',
    component: 'layout.base$view.cron',
    meta: {
      title: 'cron',
      i18nKey: 'route.cron'
    }
  },
  {
    name: 'dict',
    path: '/dict',
    component: 'layout.base',
    meta: {
      title: 'dict',
      i18nKey: 'route.dict'
    },
    children: [
      {
        name: 'dict_data',
        path: '/dict/data/:code',
        component: 'view.dict_data',
        meta: {
          title: 'dict_data',
          i18nKey: 'route.dict_data'
        }
      },
      {
        name: 'dict_type',
        path: '/dict/type',
        component: 'view.dict_type',
        meta: {
          title: 'dict_type',
          i18nKey: 'route.dict_type'
        }
      }
    ]
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base',
    meta: {
      title: 'function',
      i18nKey: 'route.function'
    },
    children: [
      {
        name: 'function_hide-child',
        path: '/function/hide-child',
        meta: {
          title: 'function_hide-child',
          i18nKey: 'route.function_hide-child'
        },
        children: [
          {
            name: 'function_hide-child_one',
            path: '/function/hide-child/one',
            component: 'view.function_hide-child_one',
            meta: {
              title: 'function_hide-child_one',
              i18nKey: 'route.function_hide-child_one'
            }
          },
          {
            name: 'function_hide-child_three',
            path: '/function/hide-child/three',
            component: 'view.function_hide-child_three',
            meta: {
              title: 'function_hide-child_three',
              i18nKey: 'route.function_hide-child_three'
            }
          },
          {
            name: 'function_hide-child_two',
            path: '/function/hide-child/two',
            component: 'view.function_hide-child_two',
            meta: {
              title: 'function_hide-child_two',
              i18nKey: 'route.function_hide-child_two'
            }
          }
        ]
      },
      {
        name: 'function_multi-tab',
        path: '/function/multi-tab',
        component: 'view.function_multi-tab',
        meta: {
          title: 'function_multi-tab',
          i18nKey: 'route.function_multi-tab'
        }
      },
      {
        name: 'function_request',
        path: '/function/request',
        component: 'view.function_request',
        meta: {
          title: 'function_request',
          i18nKey: 'route.function_request'
        }
      },
      {
        name: 'function_super-page',
        path: '/function/super-page',
        component: 'view.function_super-page',
        meta: {
          title: 'function_super-page',
          i18nKey: 'route.function_super-page'
        }
      },
      {
        name: 'function_tab',
        path: '/function/tab',
        component: 'view.function_tab',
        meta: {
          title: 'function_tab',
          i18nKey: 'route.function_tab'
        }
      },
      {
        name: 'function_toggle-auth',
        path: '/function/toggle-auth',
        component: 'view.function_toggle-auth',
        meta: {
          title: 'function_toggle-auth',
          i18nKey: 'route.function_toggle-auth'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page'
    }
  },
  {
    name: 'logger',
    path: '/logger',
    component: 'layout.base',
    meta: {
      title: 'logger',
      i18nKey: 'route.logger'
    },
    children: [
      {
        name: 'logger_file',
        path: '/logger/file',
        component: 'view.logger_file',
        meta: {
          title: 'logger_file',
          i18nKey: 'route.logger_file'
        }
      },
      {
        name: 'logger_info',
        path: '/logger/info',
        component: 'view.logger_info',
        meta: {
          title: 'logger_info',
          i18nKey: 'route.logger_info'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.base$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage'
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user'
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail'
        }
      }
    ]
  },
  {
    name: 'project-list',
    path: '/project-list',
    component: 'layout.base$view.project-list',
    meta: {
      title: 'project-list',
      i18nKey: 'route.project-list'
    }
  },
  {
    name: 'projects',
    path: '/projects',
    component: 'layout.base',
    meta: {
      title: 'projects',
      i18nKey: 'route.projects'
    },
    children: [
      {
        name: 'projects_document',
        path: '/projects/document',
        meta: {
          title: 'projects_document',
          i18nKey: 'route.projects_document'
        },
        children: [
          {
            name: 'projects_document_api',
            path: '/projects/document/api',
            component: 'view.projects_document_api',
            meta: {
              title: 'projects_document_api',
              i18nKey: 'route.projects_document_api'
            }
          },
          {
            name: 'projects_document_files',
            path: '/projects/document/files',
            component: 'view.projects_document_files',
            meta: {
              title: 'projects_document_files',
              i18nKey: 'route.projects_document_files'
            }
          },
          {
            name: 'projects_document_knowledge',
            path: '/projects/document/knowledge',
            component: 'view.projects_document_knowledge',
            meta: {
              title: 'projects_document_knowledge',
              i18nKey: 'route.projects_document_knowledge'
            }
          },
          {
            name: 'projects_document_wiki',
            path: '/projects/document/wiki',
            component: 'view.projects_document_wiki',
            meta: {
              title: 'projects_document_wiki',
              i18nKey: 'route.projects_document_wiki'
            }
          }
        ]
      },
      {
        name: 'projects_overview',
        path: '/projects/overview',
        component: 'view.projects_overview',
        meta: {
          title: 'projects_overview',
          i18nKey: 'route.projects_overview'
        }
      },
      {
        name: 'projects_repository',
        path: '/projects/repository',
        component: 'view.projects_repository',
        meta: {
          title: 'projects_repository',
          i18nKey: 'route.projects_repository'
        }
      },
      {
        name: 'projects_synergy',
        path: '/projects/synergy',
        component: 'view.projects_synergy',
        meta: {
          title: 'projects_synergy',
          i18nKey: 'route.projects_synergy'
        }
      },
      {
        name: 'projects_test',
        path: '/projects/test',
        meta: {
          title: 'projects_test',
          i18nKey: 'route.projects_test'
        },
        children: [
          {
            name: 'projects_test_overview',
            path: '/projects/test/overview',
            component: 'view.projects_test_overview',
            meta: {
              title: 'projects_test_overview',
              i18nKey: 'route.projects_test_overview'
            }
          },
          {
            name: 'projects_test_plan',
            path: '/projects/test/plan',
            component: 'view.projects_test_plan',
            meta: {
              title: 'projects_test_plan',
              i18nKey: 'route.projects_test_plan'
            }
          },
          {
            name: 'projects_test_report',
            path: '/projects/test/report',
            component: 'view.projects_test_report',
            meta: {
              title: 'projects_test_report',
              i18nKey: 'route.projects_test_report'
            }
          },
          {
            name: 'projects_test_use-case',
            path: '/projects/test/use-case',
            component: 'view.projects_test_use-case',
            meta: {
              title: 'projects_test_use-case',
              i18nKey: 'route.projects_test_use-case'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'test-page',
    path: '/test-page',
    component: 'layout.base',
    meta: {
      title: 'test-page',
      i18nKey: 'route.test-page'
    },
    children: [
      {
        name: 'test-page_page-one',
        path: '/test-page/page-one',
        component: 'view.test-page_page-one',
        meta: {
          title: 'test-page_page-one',
          i18nKey: 'route.test-page_page-one'
        }
      },
      {
        name: 'test-page_page-two',
        path: '/test-page/page-two',
        component: 'view.test-page_page-two',
        meta: {
          title: 'test-page_page-two',
          i18nKey: 'route.test-page_page-two'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center'
    }
  }
];
