// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysDictDatum = "sys_dict_data"

// SysDictDatum 字段内容表
type SysDictDatum struct {
	ID        int32     `gorm:"column:id;primaryKey;comment:主键" json:"id"` // 主键
	DictLabel string    `gorm:"column:dict_label;not null" json:"dict_label"`
	DictValue string    `gorm:"column:dict_value;not null" json:"dict_value"`
	DictSort  int32     `gorm:"column:dict_sort;not null" json:"dict_sort"`
	Version   int32     `gorm:"column:version;comment:乐观锁" json:"version"`          // 乐观锁
	CreateUID int32     `gorm:"column:create_uid;comment:创建者uid" json:"create_uid"` // 创建者uid
	CreateBy  string    `gorm:"column:create_by;comment:创建者" json:"create_by"`      // 创建者
	CreateAt  time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`     // 创建时间
	UpdateAt  time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`     // 更新时间
	UpdateUID int32     `gorm:"column:update_uid;comment:更新者uid" json:"update_uid"` // 更新者uid
}

// TableName SysDictDatum's table name
func (*SysDictDatum) TableName() string {
	return TableNameSysDictDatum
}
