// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysGenTableColumn = "sys_gen_table_column"

// SysGenTableColumn 代码生成字段表
type SysGenTableColumn struct {
	UID             string    `gorm:"column:uid;primaryKey;default:0;comment:软删除编辑" json:"uid"`                       // 软删除编辑
	TableID         string    `gorm:"column:table_id;comment:表ID" json:"table_id"`                                    // 表ID
	ColumnUpUpName  string    `gorm:"column:column_up_up_name;comment:字段upup" json:"column_up_up_name"`               // 字段upup
	ColumnLowUpName string    `gorm:"column:column_low_up_name;comment:字段lowup" json:"column_low_up_name"`            // 字段lowup
	ColumnName      string    `gorm:"column:column_name;comment:字段名" json:"column_name"`                              // 字段名
	ColumnComment   string    `gorm:"column:column_comment;comment:列描述" json:"column_comment"`                        // 列描述
	ColumnLength    string    `gorm:"column:column_length;default:0;comment:列长度" json:"column_length"`                // 列长度
	ColumnType      string    `gorm:"column:column_type;comment:go类型" json:"column_type"`                             // go类型
	ColumnTsType    string    `gorm:"column:column_ts_type;comment:ts类型" json:"column_ts_type"`                       // ts类型
	IsRequired      bool      `gorm:"column:is_required;comment:是否必填: [1=是, 0=否]" json:"is_required"`                 // 是否必填: [1=是, 0=否]
	IsBase          bool      `gorm:"column:is_base;comment:是否基础字段" json:"is_base"`                                   // 是否基础字段
	IsEdit          bool      `gorm:"column:is_edit;comment:是否编辑字段: [1=是, 0=否]" json:"is_edit"`                       // 是否编辑字段: [1=是, 0=否]
	IsList          bool      `gorm:"column:is_list;comment:是否列表字段: [1=是, 0=否]" json:"is_list"`                       // 是否列表字段: [1=是, 0=否]
	IsQuery         bool      `gorm:"column:is_query;comment:是否查询字段: [1=是, 0=否]" json:"is_query"`                     // 是否查询字段: [1=是, 0=否]
	QueryType       string    `gorm:"column:query_type;default:EQ;comment:查询方式: [等于、不等于、大于、小于、范围]" json:"query_type"` // 查询方式: [等于、不等于、大于、小于、范围]
	HTMLType        string    `gorm:"column:html_type;comment:显示类型: [文本框、文本域、下拉框、复选框、单选框、日期控件]" json:"html_type"`     // 显示类型: [文本框、文本域、下拉框、复选框、单选框、日期控件]
	DictType        string    `gorm:"column:dict_type;comment:字典类型" json:"dict_type"`                                 // 字典类型
	Sort            int32     `gorm:"column:sort;default:1;comment:排序编号" json:"sort"`                                 // 排序编号
	Version         int32     `gorm:"column:version;comment:乐观锁" json:"version"`                                      // 乐观锁
	CreateUID       int32     `gorm:"column:create_uid;comment:创建者uid" json:"create_uid"`                             // 创建者uid
	CreateBy        string    `gorm:"column:create_by;comment:创建者" json:"create_by"`                                  // 创建者
	CreateAt        time.Time `gorm:"column:create_at;comment:创建时间" json:"create_at"`                                 // 创建时间
	UpdateAt        time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                                 // 更新时间
	UpdateUID       int32     `gorm:"column:update_uid;comment:更新者uid" json:"update_uid"`                             // 更新者uid
	SoftDeleteTag   int32     `gorm:"column:soft_delete_tag;comment:软删除标记" json:"soft_delete_tag"`                    // 软删除标记
	UpdateBy        string    `gorm:"column:update_by;comment:更新者" json:"update_by"`                                  // 更新者
}

// TableName SysGenTableColumn's table name
func (*SysGenTableColumn) TableName() string {
	return TableNameSysGenTableColumn
}
