// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysMenu = "sys_menu"

// SysMenu 系统菜单
type SysMenu struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                          // 主键
	Name             string    `gorm:"column:name;not null;comment:菜单项名称" json:"name"`                                        // 菜单项名称
	Path             string    `gorm:"column:path;not null;comment:路径" json:"path"`                                           // 路径
	Redirect         string    `gorm:"column:redirect;not null;comment:重定向地址" json:"redirect"`                                // 重定向地址
	ParentID         int32     `gorm:"column:parent_id;not null;comment:父菜单uuid" json:"parent_id"`                            // 父菜单uuid
	Component        string    `gorm:"column:component;not null;comment:组件名称" json:"component"`                               // 组件名称
	Props            int32     `gorm:"column:props;not null;comment:地址参数 u/:id" json:"props"`                                 // 地址参数 u/:id
	Status           int32     `gorm:"column:status;not null;default:1;comment:是否启用" json:"status"`                           // 是否启用
	MetaIconType     string    `gorm:"column:meta_icon_type;not null;comment:icon类型 0本地 1iconify" json:"meta_icon_type"`      // icon类型 0本地 1iconify
	MetaOrder        int32     `gorm:"column:meta_order;not null;comment:排序" json:"meta_order"`                               // 排序
	MetaConstant     int32     `gorm:"column:meta_constant;not null;comment:常量路由" json:"meta_constant"`                       // 常量路由
	MetaHideInMenu   int32     `gorm:"column:meta_hide_in_menu;not null;comment:菜单中隐藏" json:"meta_hide_in_menu"`              // 菜单中隐藏
	MetaRequiresAuth int32     `gorm:"column:meta_requires_auth;not null;default:1;comment:是否需要认证" json:"meta_requires_auth"` // 是否需要认证
	MetaIcon         string    `gorm:"column:meta_icon;not null;comment:元图标" json:"meta_icon"`                                // 元图标
	MetaLocalIcon    string    `gorm:"column:meta_local_icon;not null;comment:本地元图标" json:"meta_local_icon"`                  // 本地元图标
	MetaI18nKey      string    `gorm:"column:meta_i18n_key;not null;comment:国际化标题" json:"meta_i18n_key"`                      // 国际化标题
	MetaHref         string    `gorm:"column:meta_href;not null;comment:外部连接" json:"meta_href"`                               // 外部连接
	MetaKeepAlive    int32     `gorm:"column:meta_keep_alive;not null;default:1;comment:缓存该路由" json:"meta_keep_alive"`        // 缓存该路由
	MetaTitle        string    `gorm:"column:meta_title;not null;comment:元数据标题" json:"meta_title"`                            // 元数据标题
	MetaActiveMenu   string    `gorm:"column:meta_active_menu;not null;comment:激活的菜单键" json:"meta_active_menu"`               // 激活的菜单键
	MetaMultiTab     int32     `gorm:"column:meta_multi_tab;not null;comment:多个标签页" json:"meta_multi_tab"`                    // 多个标签页
	MetaFixedInTab   int32     `gorm:"column:meta_fixed_in_tab;comment:标签固定位置" json:"meta_fixed_in_tab"`                      // 标签固定位置
	MetaQuery        string    `gorm:"column:meta_query;not null;comment:默认携带参数" json:"meta_query"`                           // 默认携带参数
	Version          int32     `gorm:"column:version;not null;comment:乐观锁" json:"version"`                                    // 乐观锁
	SoftDeleteTag    int32     `gorm:"column:soft_delete_tag;not null;comment:软删除标记" json:"soft_delete_tag"`                  // 软删除标记
	UpdateTime       time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`                                    // 更新时间
	UpdateUID        int32     `gorm:"column:update_uid;comment:更新者uuid" json:"update_uid"`                                   // 更新者uuid
	CreateUID        int32     `gorm:"column:create_uid;comment:创建者uuid" json:"create_uid"`                                   // 创建者uuid
	CreateBy         string    `gorm:"column:create_by;comment:创建者" json:"create_by"`                                         // 创建者
	CreateTime       time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`                                    // 创建时间
	UpdateBy         string    `gorm:"column:update_by;comment:更新者名称" json:"update_by"`                                       // 更新者名称
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}
