// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysDictDatum = "sys_dict_data"

// SysDictDatum mapped from table <sys_dict_data>
type SysDictDatum struct {
	ID         int32     `gorm:"column:id;type:int(11);primaryKey;comment:主键" json:"id"` // 主键
	DictLabel  string    `gorm:"column:dict_label;type:varchar(255);not null" json:"dictLabel"`
	DictValue  string    `gorm:"column:dict_value;type:varchar(255);not null" json:"dictValue"`
	DictSort   int32     `gorm:"column:dict_sort;type:int(11);not null" json:"dictSort"`
	Version    int32     `gorm:"column:version;type:int(11);comment:乐观锁" json:"version"`                               // 乐观锁
	CreateUID  int32     `gorm:"column:create_uid;type:int(11);comment:创建者uid" json:"createUid"`                       // 创建者uid
	CreateBy   string    `gorm:"column:create_by;type:varchar(255);comment:创建者" json:"createBy"`                       // 创建者
	CreateTime time.Time `gorm:"column:create_time;type:datetime;autoCreateTime:milli;comment:创建时间" json:"createTime"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;autoUpdateTime:milli;comment:更新时间" json:"updateTime"` // 更新时间
	UpdateUID  int32     `gorm:"column:update_uid;type:int(11);comment:更新者uid" json:"updateUid"`                       // 更新者uid
}

// TableName SysDictDatum's table name
func (*SysDictDatum) TableName() string {
	return TableNameSysDictDatum
}
