// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysOauth2Bind = "sys_oauth2_bind"

// SysOauth2Bind mapped from table <sys_oauth2_bind>
type SysOauth2Bind struct {
	UserUID      string `gorm:"column:user_uid;primaryKey;comment:本系统用户的ID" json:"user_uid"` // 本系统用户的ID
	PlatformCode string `gorm:"column:platform_code;comment:三方平台代码" json:"platform_code"`    // 三方平台代码
	PlatformUID  string `gorm:"column:platform_uid;comment:三方平台用户ID" json:"platform_uid"`    // 三方平台用户ID
}

// TableName SysOauth2Bind's table name
func (*SysOauth2Bind) TableName() string {
	return TableNameSysOauth2Bind
}
