// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysAPI = "sys_api"

// SysAPI mapped from table <sys_api>
type SysAPI struct {
	APICode       string    `gorm:"column:api_code;comment:标记GET::/api" json:"api_code"`                  // 标记GET::/api
	Version       int32     `gorm:"column:version;not null;comment:乐观锁" json:"version"`                   // 乐观锁
	SoftDeleteTag int32     `gorm:"column:soft_delete_tag;not null;comment:软删除标记" json:"soft_delete_tag"` // 软删除标记
	UpdateTime    time.Time `gorm:"column:update_time;not null;comment:更新时间" json:"update_time"`          // 更新时间
	UpdateUID     int32     `gorm:"column:update_uid;not null;comment:更新者uuid" json:"update_uid"`         // 更新者uuid
	CreateUID     int32     `gorm:"column:create_uid;not null;comment:创建者uuid" json:"create_uid"`         // 创建者uuid
	CreateBy      string    `gorm:"column:create_by;not null;comment:创建者" json:"create_by"`               // 创建者
	CreateTime    time.Time `gorm:"column:create_time;not null;comment:创建时间" json:"create_time"`          // 创建时间
	UpdateBy      string    `gorm:"column:update_by;not null;comment:更新者名称" json:"update_by"`             // 更新者名称
}

// TableName SysAPI's table name
func (*SysAPI) TableName() string {
	return TableNameSysAPI
}
