// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysGenTableColumn = "sys_gen_table_column"

// SysGenTableColumn mapped from table <sys_gen_table_column>
type SysGenTableColumn struct {
	UID             string    `gorm:"column:uid;type:varchar(200);primaryKey;default:0;comment:软删除编辑" json:"uid"`                     // 软删除编辑
	TableID         string    `gorm:"column:table_id;type:varchar(200);comment:表ID" json:"tableId"`                                   // 表ID
	ColumnUpUpName  string    `gorm:"column:column_up_up_name;type:varchar(255);comment:字段upup" json:"columnUpUpName"`                // 字段upup
	ColumnLowUpName string    `gorm:"column:column_low_up_name;type:varchar(255);comment:字段lowup" json:"columnLowUpName"`             // 字段lowup
	ColumnName      string    `gorm:"column:column_name;type:varchar(255);comment:字段名" json:"columnName"`                             // 字段名
	ColumnComment   string    `gorm:"column:column_comment;type:varchar(200);comment:列描述" json:"columnComment"`                       // 列描述
	ColumnLength    string    `gorm:"column:column_length;type:varchar(5);default:0;comment:列长度" json:"columnLength"`                 // 列长度
	ColumnType      string    `gorm:"column:column_type;type:varchar(100);comment:go类型" json:"columnType"`                            // go类型
	ColumnTsType    string    `gorm:"column:column_ts_type;type:varchar(100);comment:ts类型" json:"columnTsType"`                       // ts类型
	IsRequired      int32     `gorm:"column:is_required;type:tinyint(1) unsigned;comment:是否必填: [1=是, 0=否]" json:"isRequired"`         // 是否必填: [1=是, 0=否]
	IsBase          int32     `gorm:"column:is_base;type:tinyint(1) unsigned zerofill;comment:是否基础字段" json:"isBase"`                  // 是否基础字段
	IsEdit          int32     `gorm:"column:is_edit;type:tinyint(1) unsigned;comment:是否编辑字段: [1=是, 0=否]" json:"isEdit"`               // 是否编辑字段: [1=是, 0=否]
	IsList          int32     `gorm:"column:is_list;type:tinyint(1) unsigned;comment:是否列表字段: [1=是, 0=否]" json:"isList"`               // 是否列表字段: [1=是, 0=否]
	IsQuery         int32     `gorm:"column:is_query;type:tinyint(1) unsigned;comment:是否查询字段: [1=是, 0=否]" json:"isQuery"`             // 是否查询字段: [1=是, 0=否]
	QueryType       string    `gorm:"column:query_type;type:varchar(30);default:EQ;comment:查询方式: [等于、不等于、大于、小于、范围]" json:"queryType"` // 查询方式: [等于、不等于、大于、小于、范围]
	HTMLType        string    `gorm:"column:html_type;type:varchar(30);comment:显示类型: [文本框、文本域、下拉框、复选框、单选框、日期控件]" json:"htmlType"`     // 显示类型: [文本框、文本域、下拉框、复选框、单选框、日期控件]
	DictType        string    `gorm:"column:dict_type;type:varchar(200);comment:字典类型" json:"dictType"`                                // 字典类型
	Sort            int32     `gorm:"column:sort;type:smallint(5) unsigned;default:1;comment:排序编号" json:"sort"`                       // 排序编号
	Version         int32     `gorm:"column:version;type:int(11);comment:乐观锁" json:"version"`                                         // 乐观锁
	CreateUID       int32     `gorm:"column:create_uid;type:int(11);comment:创建者uid" json:"createUid"`                                 // 创建者uid
	CreateBy        string    `gorm:"column:create_by;type:varchar(255);comment:创建者" json:"createBy"`                                 // 创建者
	CreateTime      time.Time `gorm:"column:create_time;type:datetime;autoCreateTime:milli;comment:创建时间" json:"createTime"`           // 创建时间
	UpdateTime      time.Time `gorm:"column:update_time;type:datetime;autoUpdateTime:milli;comment:更新时间" json:"updateTime"`           // 更新时间
	UpdateUID       int32     `gorm:"column:update_uid;type:int(11);comment:更新者uid" json:"updateUid"`                                 // 更新者uid
	SoftDeleteTag   int32     `gorm:"column:soft_delete_tag;type:tinyint(10);comment:软删除标记" json:"softDeleteTag"`                     // 软删除标记
	UpdateBy        string    `gorm:"column:update_by;type:varchar(255);comment:更新者" json:"updateBy"`                                 // 更新者
}

// TableName SysGenTableColumn's table name
func (*SysGenTableColumn) TableName() string {
	return TableNameSysGenTableColumn
}
