// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysOauth2Bind = "sys_oauth2_bind"

// SysOauth2Bind mapped from table <sys_oauth2_bind>
type SysOauth2Bind struct {
	UserUID      string `gorm:"column:user_uid;type:varchar(255);primaryKey;comment:本系统用户的ID" json:"userUid"` // 本系统用户的ID
	PlatformCode string `gorm:"column:platform_code;type:varchar(255);comment:三方平台代码" json:"platformCode"`    // 三方平台代码
	PlatformUID  string `gorm:"column:platform_uid;type:varchar(255);comment:三方平台用户ID" json:"platformUid"`    // 三方平台用户ID
}

// TableName SysOauth2Bind's table name
func (*SysOauth2Bind) TableName() string {
	return TableNameSysOauth2Bind
}
