Gorm: # 只针对 gorm  操作数据库有效
  Mysql:
    IsInitGlobalGormMysql: 1    # 随项目启动为gorm db初始化一个全局 xvariable.GormDbMysql（完全等于*gorm.Db）,正确配置数据库，该值必须设置为: 1
    SlowThreshold: 30            # 慢 SQL 阈值(sql执行时间超过此时间单位（秒），就会触发系统日志记录)
    Host: "xiaos.cool"
    DataBase: "xiaos_core_new"
    Port: 3306
    User: "xiaos_core_new"
    Pass: "5SJPJXbMFbyJEKp5"  # 修改为你自己的数据库密码
    Charset: "utf8mb4"
    SetMaxIdleConn: 10
    SetMaxOpenConn: 128
    SetConnMaxLifetime: 60    # 连接不活动时的最大生存时间(秒)

